#user_input=input("Enter some text:")
#print("You entered:",user_input)
num_1 = input("Enter the first number:")
num_2 = input("Enter the second number:")
result = int(num_1) % int(num_2)
print("The result is ", result)